<script lang='ts' context='module'>
	import * as hl from 'svelte-highlight/src/languages/index';

	export const tableOfLanguages: Record<string, hl.HljsLanguage> = {
		'1c': hl._1c,
		'abnf': hl.abnf,
		'accesslog': hl.accesslog,
		'actionscript': hl.actionscript,
		'ada': hl.ada,
		'angelscript': hl.angelscript,
		'apache': hl.apache,
		'applescript': hl.applescript,
		'arcade': hl.arcade,
		'arduino': hl.arduino,
		'armasm': hl.armasm,
		'asciidoc': hl.asciidoc,
		'aspectj': hl.aspectj,
		'autohotkey': hl.autohotkey,
		'autoit': hl.autoit,
		'avrasm': hl.avrasm,
		'awk': hl.awk,
		'axapta': hl.axapta,
		'bash': hl.bash,
		'basic': hl.basic,
		'bnf': hl.bnf,
		'brainfuck': hl.brainfuck,
		'c': hl.c,
		'cal': hl.cal,
		'capnproto': hl.capnproto,
		'ceylon': hl.ceylon,
		'clean': hl.clean,
		'clojure-repl': hl.clojureRepl,
		'clojure': hl.clojure,
		'cmake': hl.cmake,
		'coffeescript': hl.coffeescript,
		'coq': hl.coq,
		'cos': hl.cos,
		'cpp': hl.cpp,
		'crmsh': hl.crmsh,
		'crystal': hl.crystal,
		'csharp': hl.csharp,
		'csp': hl.csp,
		'css': hl.css,
		'd': hl.d,
		'dart': hl.dart,
		'delphi': hl.delphi,
		'diff': hl.diff,
		'django': hl.django,
		'dns': hl.dns,
		'dockerfile': hl.dockerfile,
		'dos': hl.dos,
		'dsconfig': hl.dsconfig,
		'dts': hl.dts,
		'dust': hl.dust,
		'ebnf': hl.ebnf,
		'elixir': hl.elixir,
		'elm': hl.elm,
		'erb': hl.erb,
		'erlang-repl': hl.erlangRepl,
		'erlang': hl.erlang,
		'excel': hl.excel,
		'fix': hl.fix,
		'flix': hl.flix,
		'fortran': hl.fortran,
		'fsharp': hl.fsharp,
		'gams': hl.gams,
		'gauss': hl.gauss,
		'gcode': hl.gcode,
		'gherkin': hl.gherkin,
		'glsl': hl.glsl,
		'gml': hl.gml,
		'go': hl.go,
		'golo': hl.golo,
		'gradle': hl.gradle,
		'groovy': hl.groovy,
		'haml': hl.haml,
		'handlebars': hl.handlebars,
		'haskell': hl.haskell,
		'haxe': hl.haxe,
		'hsp': hl.hsp,
		'http': hl.http,
		'hy': hl.hy,
		'inform7': hl.inform7,
		'ini': hl.ini,
		'irpf90': hl.irpf90,
		'isbl': hl.isbl,
		'java': hl.java,
		'javascript': hl.javascript,
		'jboss-cli': hl.jbossCli,
		'json': hl.json,
		'julia-repl': hl.juliaRepl,
		'julia': hl.julia,
		'kotlin': hl.kotlin,
		'lasso': hl.lasso,
		'latex': hl.latex,
		'ldif': hl.ldif,
		'leaf': hl.leaf,
		'less': hl.less,
		'lisp': hl.lisp,
		'livecodeserver': hl.livecodeserver,
		'livescript': hl.livescript,
		'llvm': hl.llvm,
		'lsl': hl.lsl,
		'lua': hl.lua,
		'makefile': hl.makefile,
		'markdown': hl.markdown,
		'mathematica': hl.mathematica,
		'matlab': hl.matlab,
		'maxima': hl.maxima,
		'mel': hl.mel,
		'mercury': hl.mercury,
		'mipsasm': hl.mipsasm,
		'mizar': hl.mizar,
		'mojolicious': hl.mojolicious,
		'monkey': hl.monkey,
		'moonscript': hl.moonscript,
		'n1ql': hl.n1ql,
		'nestedtext': hl.nestedtext,
		'nginx': hl.nginx,
		'nim': hl.nim,
		'nix': hl.nix,
		'node-repl': hl.nodeRepl,
		'nsis': hl.nsis,
		'objectivec': hl.objectivec,
		'ocaml': hl.ocaml,
		'openscad': hl.openscad,
		'oxygene': hl.oxygene,
		'parser3': hl.parser3,
		'perl': hl.perl,
		'pf': hl.pf,
		'pgsql': hl.pgsql,
		'php-template': hl.phpTemplate,
		'php': hl.php,
		'plaintext': hl.plaintext,
		'pony': hl.pony,
		'powershell': hl.powershell,
		'processing': hl.processing,
		'profile': hl.profile,
		'prolog': hl.prolog,
		'properties': hl.properties,
		'protobuf': hl.protobuf,
		'puppet': hl.puppet,
		'purebasic': hl.purebasic,
		'python-repl': hl.pythonRepl,
		'python': hl.python,
		'q': hl.q,
		'qml': hl.qml,
		'r': hl.r,
		'reasonml': hl.reasonml,
		'rib': hl.rib,
		'roboconf': hl.roboconf,
		'routeros': hl.routeros,
		'rsl': hl.rsl,
		'ruby': hl.ruby,
		'ruleslanguage': hl.ruleslanguage,
		'rust': hl.rust,
		'sas': hl.sas,
		'scala': hl.scala,
		'scheme': hl.scheme,
		'scilab': hl.scilab,
		'scss': hl.scss,
		'shell': hl.shell,
		'smali': hl.smali,
		'smalltalk': hl.smalltalk,
		'sml': hl.sml,
		'sqf': hl.sqf,
		'sql': hl.sql,
		'stan': hl.stan,
		'stata': hl.stata,
		'step21': hl.step21,
		'stylus': hl.stylus,
		'subunit': hl.subunit,
		'swift': hl.swift,
		'taggerscript': hl.taggerscript,
		'tap': hl.tap,
		'tcl': hl.tcl,
		'thrift': hl.thrift,
		'tp': hl.tp,
		'twig': hl.twig,
		'typescript': hl.typescript,
		'vala': hl.vala,
		'vbnet': hl.vbnet,
		'vbscript-html': hl.vbscriptHtml,
		'vbscript': hl.vbscript,
		'verilog': hl.verilog,
		'vhdl': hl.vhdl,
		'vim': hl.vim,
		'wasm': hl.wasm,
		'wren': hl.wren,
		'x86asm': hl.x86asm,
		'xl': hl.xl,
		'xml': hl.xml,
		'xquery': hl.xquery,
		'yaml': hl.yaml,
		'zephir': hl.zephir,
	};

	export type LanguageName =
		| '1c'
		| 'abnf'
		| 'accesslog'
		| 'actionscript'
		| 'ada'
		| 'angelscript'
		| 'apache'
		| 'applescript'
		| 'arcade'
		| 'arduino'
		| 'armasm'
		| 'asciidoc'
		| 'aspectj'
		| 'autohotkey'
		| 'autoit'
		| 'avrasm'
		| 'awk'
		| 'axapta'
		| 'bash'
		| 'basic'
		| 'bnf'
		| 'brainfuck'
		| 'c'
		| 'cal'
		| 'capnproto'
		| 'ceylon'
		| 'clean'
		| 'clojure-repl'
		| 'clojure'
		| 'cmake'
		| 'coffeescript'
		| 'coq'
		| 'cos'
		| 'cpp'
		| 'crmsh'
		| 'crystal'
		| 'csharp'
		| 'csp'
		| 'css'
		| 'd'
		| 'dart'
		| 'delphi'
		| 'diff'
		| 'django'
		| 'dns'
		| 'dockerfile'
		| 'dos'
		| 'dsconfig'
		| 'dts'
		| 'dust'
		| 'ebnf'
		| 'elixir'
		| 'elm'
		| 'erb'
		| 'erlang-repl'
		| 'erlang'
		| 'excel'
		| 'fix'
		| 'flix'
		| 'fortran'
		| 'fsharp'
		| 'gams'
		| 'gauss'
		| 'gcode'
		| 'gherkin'
		| 'glsl'
		| 'gml'
		| 'go'
		| 'golo'
		| 'gradle'
		| 'groovy'
		| 'haml'
		| 'handlebars'
		| 'haskell'
		| 'haxe'
		| 'hsp'
		| 'http'
		| 'hy'
		| 'index'
		| 'inform7'
		| 'ini'
		| 'irpf90'
		| 'isbl'
		| 'java'
		| 'javascript'
		| 'jboss-cli'
		| 'json'
		| 'julia-repl'
		| 'julia'
		| 'kotlin'
		| 'lasso'
		| 'latex'
		| 'ldif'
		| 'leaf'
		| 'less'
		| 'lisp'
		| 'livecodeserver'
		| 'livescript'
		| 'llvm'
		| 'lsl'
		| 'lua'
		| 'makefile'
		| 'markdown'
		| 'mathematica'
		| 'matlab'
		| 'maxima'
		| 'mel'
		| 'mercury'
		| 'mipsasm'
		| 'mizar'
		| 'mojolicious'
		| 'monkey'
		| 'moonscript'
		| 'n1ql'
		| 'nestedtext'
		| 'nginx'
		| 'nim'
		| 'nix'
		| 'node-repl'
		| 'nsis'
		| 'objectivec'
		| 'ocaml'
		| 'openscad'
		| 'oxygene'
		| 'parser3'
		| 'perl'
		| 'pf'
		| 'pgsql'
		| 'php-template'
		| 'php'
		| 'plaintext'
		| 'pony'
		| 'powershell'
		| 'processing'
		| 'profile'
		| 'prolog'
		| 'properties'
		| 'protobuf'
		| 'puppet'
		| 'purebasic'
		| 'python-repl'
		| 'python'
		| 'q'
		| 'qml'
		| 'r'
		| 'reasonml'
		| 'rib'
		| 'roboconf'
		| 'routeros'
		| 'rsl'
		| 'ruby'
		| 'ruleslanguage'
		| 'rust'
		| 'sas'
		| 'scala'
		| 'scheme'
		| 'scilab'
		| 'scss'
		| 'shell'
		| 'smali'
		| 'smalltalk'
		| 'sml'
		| 'sqf'
		| 'sql'
		| 'stan'
		| 'stata'
		| 'step21'
		| 'stylus'
		| 'subunit'
		| 'swift'
		| 'taggerscript'
		| 'tap'
		| 'tcl'
		| 'thrift'
		| 'tp'
		| 'twig'
		| 'typescript'
		| 'vala'
		| 'vbnet'
		| 'vbscript-html'
		| 'vbscript'
		| 'verilog'
		| 'vhdl'
		| 'vim'
		| 'wasm'
		| 'wren'
		| 'x86asm'
		| 'xl'
		| 'xml'
		| 'xquery'
		| 'yaml'
		| 'zephir'
</script>

<script lang='ts'>
	import Highlight from 'svelte-highlight';

	export let lang: LanguageName;
	export let code: string;
</script>

<Highlight language={
		lang.toLowerCase() in tableOfLanguages ? tableOfLanguages[lang.toLowerCase()]
	: tableOfLanguages.plaintext
} {code} />
